framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis
        prefix_seed: 'cloudcart'
        default_redis_provider: app.redis_client

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

        # Namespaced pools use the above "app" backend by default
        pools:
            redis:
                adapters:
                    - cache.adapter.redis_tag_aware
                public: true
            doctrine.system_cache_pool:
                adapter:
                    - cache.adapter.redis_tag_aware
                public: true

services:
    app.redis_client:
        class: \Redis
        factory: ['Symfony\Component\Cache\Adapter\RedisTagAwareAdapter', 'createConnection']
        arguments:
            - '%env(CACHE_URL)%'
            - {
                  lazy: false,
                  retry_interval: 0,
                  timeout: 30,
                  tcp_keepalive: 300,
            }
    app.runtime_cache:
        class: Symfony\Component\Cache\Adapter\ArrayAdapter
        arguments:
            - 0
            - false
