framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(MAILER_SENDER)%'

when@dev:
    framework:
        mailer:
            envelope:
                recipients: ['%env(MAILER_SENDER)%']
